name: Build/Test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/nuget_readme.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/nuget_readme.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .Net 7.x
      run: dotnet build -f net7.0 -c Release

    - name: Build .Net 6.x
      run: dotnet build -f net6.0 -c Release

    - name: Build NetStandard 2.0
      run: dotnet build -f netstandard2.0 -c Release

    - name: Test
      run: dotnet test --no-build
